# Generated by Django 5.1.7 on 2025-03-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roll',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
